rabbitmq:
  image: "rabbitmq:management"
  hostname: "rabbit"
  environment:
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "admin"
    RABBITMQ_DEFAULT_VHOST: "/"
    RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS : -rabbitmq_management load_definitions "/tmp/rabbit.definitions.json"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq"
  volumes:
    - './enabled_plugins:/etc/rabbitmq/enabled_plugins'
    - './definitions.json:/tmp/rabbit.definitions.json:ro'